In [1]:
pip install numpy


Defaulting to user installation because normal site-packages is not writeable
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     -------------------- ------------------- 30.7/61.0 kB ? eta -:--:--
     -------------------------------------- 61.0/61.0 kB 806.3 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.2/15.5 MB 4.6 MB/s eta 0:00:04
   ---------------------------------------- 0.2/15.5 MB 4.6 MB/s eta 0:00:04
    --------------------------------------- 0.3/15.5 MB 2.0 MB/s eta 0:00:08
    --------------------------------------- 0.3/15.5 MB 1.9 MB/s eta 0:00:08
    --------------------------------------- 0.4/15.5 MB 1.6 MB/s eta 0:00:10
   - -------------------------------------- 0.4/15.5 MB 1.6 MB/s eta 0:00:10
   - -------------------------------------- 0.4/15.5 MB 1.4 MB/s eta 0:00:11
   - -------------


[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np


In [11]:
random_int_array = np.random.randint(1, 50, size=(10))
random_int_array

array([36, 30,  9, 28, 15, 48, 14, 29, 40, 25])

In [13]:
avarage=np.mean(random_int_array)
avarage

27.4

In [15]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr = np.arange(1, 11)
np.random.shuffle(arr)
arr

array([ 4,  3,  5,  2,  8,  9,  6,  7,  1, 10])

In [18]:
arr = np.arange(1, 11)
np.random.shuffle(arr)
random_selected_element=np.random.choice(arr,size=3,replace=False)
random_selected_element

array([ 8, 10,  5])

In [19]:
arr = np.arange(1, 11)
np.random.shuffle(arr)
random_selected_element=np.random.choice(arr,size=1,replace=False)
random_selected_element

array([4])