In [1]:
pip install numpy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np


In [11]:
random_int_array = np.random.randint(1, 50, size=(10))
random_int_array

array([36, 30,  9, 28, 15, 48, 14, 29, 40, 25])

In [13]:
avarage=np.mean(random_int_array)
avarage

27.4

In [3]:
two_dim = np.array([[1, 2, 3], [4, 5, 6], [5, 6, 7]])
two_dim

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7]])

In [15]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
a = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]])
b = np.array([[10,11,12], [13,14,15], [16,17,18]])
ab = np.add(a, b)
ab
np.mean(ab)

19.0

In [6]:
arr = np.random.randint(1, 100, size=(20))
condition = arr > 50
filtered_arr = arr[condition]
filtered_arr

array([61, 87, 88, 96, 53, 62, 97, 52, 84, 98])

In [16]:
arr = np.arange(1, 11)
np.random.shuffle(arr)
arr

array([ 4,  3,  5,  2,  8,  9,  6,  7,  1, 10])

In [18]:
arr = np.arange(1, 11)
np.random.shuffle(arr)
random_selected_element=np.random.choice(arr,size=3,replace=False)
random_selected_element

array([ 8, 10,  5])

In [19]:
arr = np.arange(1, 11)
np.random.shuffle(arr)
random_selected_element=np.random.choice(arr,size=1,replace=False)
random_selected_element

array([4])